### ISSUE TITLE
Possible unhandled Promise Rejection (id: 0) "session not found"

### ISSUE THREAD

**Issue by alecbrito** [rootstrap/react-native-base#70]
I seem to be getting a session not found an error when I attempt to create a new user or log in. I'm trying to add a user to the rails backend but I get user already exists which is not true because I can't log in with that user either.

The log shows session not found. Is there something I'm missing?

![Simulator Screen Shot - iPhone Xʀ - 2019-06-13 at 09 54 40](https://user-images.githubusercontent.com/51780173/59419169-3ee6dd80-8dc2-11e9-8bb4-d30c89d7189f.png)

![Simulator Screen Shot - iPhone Xʀ - 2019-06-13 at 09 55 07](https://user-images.githubusercontent.com/51780173/59419198-4efebd00-8dc2-11e9-9577-ba14960f0483.png)

**Comment by peter7z** [comment]
Closing as this issue is probably related to the API the user is using.
